spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
name = "PlanetScale-F1"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "ui"
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.0.1/spin_static_fs.wasm", digest = "sha256:650376c33a0756b1a52cad7ca670f1126391b79050df0321407da9c741d32375" }
files = [ { source = "out/", destination = "/" } ]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"

[[component]]
id = "api"
source = "api/target/spin-http-js.wasm"
allowed_http_hosts = ["https://aws.connect.psdb.cloud"]
files = ["auth.json"]
[component.trigger]
route = "/data.json"
[component.build]
command = "npm run build"
workdir = "api"

